# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id = $(client_id) -var client_secret =$(client_secret) -var ssh_public_key= $(ssh_public_key)'
    backendType: 'azurerm'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-resource-group'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountIAACK8S'
    backendAzureRmContainerName: 'storageaccountIAACK8S'
    backendAzureRmKey: 'K8S-IAAC-DEV'
    allowTelemetryCollection: true

