
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Hello, world!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id = $(client_id) -var client_secret =$(client_secret) -var ssh_public_key= $(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-service-manager-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-resource-group'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctasrinub4uxyz'
    backendAzureRmContainerName: 'storagecontainer'
    backendAzureRmKey: 'k8s-iaac-dev.tfstate'

